baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hyde'
DefaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.fr]
    title = "Mon dÃ©monstrateur dâ€™internationalisation"
    contentDir = "content/fr"
    languageName = 'FranÃ§ais'
    languageFlag = "ğŸ‡«ğŸ‡·"
    weight = 3
  [languages.ar]
    title = "Ù…ÙØ³ØªØ¹Ø±ÙØ¶ÙŠ Ù„Ù„ØªØ¯ÙˆÙŠÙ„"
    contentDir = "content/ar"
    languageName = 'Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©'
    languageFlag = "(ar)"
    weight = 3
  [languages.oc]
    title = "Lo meu demostrator dâ€™internacionalizacion"
    contentDir = "content/oc"
    languageName = 'occitan'
    languageFlag = "(oc)"
    weight = 3
  [languages.en]
    title = "My internationalization demonstrator"
    contentDir = "content/en"
    languageName = 'Engish'
    languageFlag = "(en)"
    weight = 1
  [languages.ro]
    title = "Demonstratorul meu de internaÈ›ionalizare"
    contentDir = "content/ro"
    languageName = 'RomÃ¢nÄƒ'
    languageFlag = "(ro)"
    weight = 3
  [languages.qq]
    title = "QMyq qinternationalizationq qdemonstratorq"
    contentDir = "content/qq"
    languageName = 'qlangq'
    languageFlag = "(qq)"
    weight = 3
  [languages.zz]
    title = "ZMyz zinternationalizationz zdemonstratorz"
    contentDir = "content/zz"
    languageName = 'zlangz'
    languageFlag = "(zz)"
    weight = 3
